### ISSUE TITLE
[Postgresql & Backend] Postgresql 컨테이너 세팅 후 Backend 컨테이너 구동되도록 처리 필요

### ISSUE THREAD

**Issue by OZestina** [42Seoul-Tea42/service#3]
### **겪은 문제나 버그에 대해서 알려주세요**
> Backend 컨테이너 시작 시 애플리케이션의 세팅을 위해 DB인 Postgresql 컨테이너와의 접속을 시도합니다
이 때 Postgresql 내부에서 DB세팅이 완료되지 않았을 경우 Backend->Postgresql 연결이 되지 않아 문제가 발생합니다.

### **어떤 상황인가요?**
> Postgresql 컨테이너 내부의 DB 세팅이 완료되지 않은 상태에서 Backend에서 연결 요청을 합니다.

**Comment by OZestina** [comment]
### docker compose의 healthcheck를 적용해 해결

**postgresql에 healthcheck 구문 추가**
- Dockerfile 내에 DB를 세팅하기 위해 POSTGRES_USER를 만드는 내용이 있고, 해당 유저가 만들어졌는지 여부를 바탕으로 check를 하는 항목 생성
- 참고 링크: [공식문서](https://docs.docker.com/compose/compose-file/05-services/#healthcheck)
```
  postgresql:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 30s
```

**backend에 condition 구문 추가**
- 기존의 depends_on에 더해 service의 healthy 여부를 확인하는 내용을 추가
- 참고 링크: [공식문서](https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1)
```
  backend:
    depends_on:
      postgresql:
        condition: service_healthy
```
